import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    category: "General",
    questions: [
      {
        q: "What is Bareter?",
        a: "Bareter is UAE's premier barter marketplace where verified businesses can trade goods and services without using cash. Instead of paying money, you exchange your products or services for what you need from other businesses.",
      },
      {
        q: "Who can use Bareter?",
        a: "Bareter is designed for businesses and professionals in the UAE and GCC region. Whether you're a hotel, a marketing agency, a freelance designer, or any other business, you can join and start bartering.",
      },
      {
        q: "Is Bareter free to use?",
        a: "Yes. Bareter is completely free for everyone. Creating an account, listing your offers, proposing trades, generating contracts, and completing deals are all free.",
      },
      {
        q: "How is Bareter different from other marketplaces?",
        a: "Unlike traditional marketplaces, Bareter focuses on barter exchanges rather than cash transactions. We provide verified business profiles, legally binding contracts, VAT compliance tools, and a structured deal flow specifically designed for B2B bartering.",
      },
    ],
  },
  {
    category: "Bartering",
    questions: [
      {
        q: "How do I propose a trade?",
        a: "Browse listings to find something you need, click 'Propose Trade', then select what you're offering in return along with its retail value. The listing owner will receive your proposal and can accept, negotiate, or decline.",
      },
      {
        q: "What if the values don't match exactly?",
        a: "Trade values don't need to be exactly equal. You can negotiate in the chat to add additional items, services, or agree on partial trades. The goal is for both parties to feel the exchange is fair.",
      },
      {
        q: "Can I trade with multiple parties at once?",
        a: "Yes, you can have multiple active deals at the same time. Each deal has its own chat and contract, making it easy to manage multiple trades simultaneously.",
      },
      {
        q: "What happens if a deal falls through?",
        a: "Either party can cancel a deal at any stage before completion. We encourage open communication to resolve issues before cancellation.",
      },
      {
        q: "How do I complete a deal?",
        a: "Once both parties have delivered, each side marks the deal as complete. As soon as both confirmations are in, the deal moves to 'completed' and you can rate each other.",
      },
    ],
  },
  {
    category: "Contracts & Legal",
    questions: [
      {
        q: "Are barter contracts legally binding?",
        a: "Yes, the contracts generated by Bareter are legally binding agreements under UAE law. They include all essential terms: what each party provides, declared values, timelines, and deliverables.",
      },
      {
        q: "Do I need to pay VAT on barter trades?",
        a: "Yes, under UAE FTA regulations, barter transactions are subject to 5% VAT based on the open market value of goods/services exchanged. Both parties should issue VAT tax invoices. Our contracts include this clause as a reminder.",
      },
      {
        q: "How do digital signatures work?",
        a: "When both parties accept the final terms, you can digitally sign the contract. This creates a PDF document with both signatures, timestamps, and a unique deal ID for your records.",
      },
    ],
  },
  {
    category: "Trust & Safety",
    questions: [
      {
        q: "How does business verification work?",
        a: "Upload your trade license, commercial registration, or Emirates ID. Our team reviews the document within 1-2 business days. Once verified, you'll receive a verified badge on your profile.",
      },
      {
        q: "What if someone doesn't deliver on their promise?",
        a: "First, try to resolve the issue through the deal chat. If that fails, you can report the issue to our support team. We review disputes and may suspend accounts that repeatedly fail to deliver.",
      },
      {
        q: "How do ratings and reviews work?",
        a: "After completing a deal, both parties can rate each other (1-5 stars) and leave a review. These ratings are public and help build trust in the community. You can only rate someone after completing a real trade with them.",
      },
    ],
  },
];

export function FAQPage() {
  return (
    <div className="container px-4 py-12 mx-auto max-w-4xl">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold mb-4">Frequently Asked Questions</h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Everything you need to know about bartering on Bareter
        </p>
      </div>

      <div className="space-y-8">
        {faqs.map((section) => (
          <div key={section.category}>
            <h2 className="text-xl font-semibold mb-4">{section.category}</h2>
            <Accordion type="single" collapsible className="space-y-2">
              {section.questions.map((faq, index) => (
                <AccordionItem
                  key={index}
                  value={`${section.category}-${index}`}
                  className="border rounded-lg px-4"
                >
                  <AccordionTrigger className="text-left hover:no-underline py-4">
                    {faq.q}
                  </AccordionTrigger>
                  <AccordionContent className="text-muted-foreground pb-4">
                    {faq.a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        ))}
      </div>

      <div className="mt-12 text-center bg-muted/30 rounded-2xl p-8">
        <h2 className="text-xl font-semibold mb-4">Still have questions?</h2>
        <p className="text-muted-foreground mb-6">
          Can't find the answer you're looking for? Our support team is here to help.
        </p>
        <div className="flex gap-4 justify-center flex-wrap">
          <Link href="/help">
            <Button variant="outline" data-testid="link-help-center">Visit Help Center</Button>
          </Link>
          <Button data-testid="button-contact-support">
            Contact Support
          </Button>
        </div>
      </div>
    </div>
  );
}
